name: CMake CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
          - os: 'ubuntu-24.04-arm'
          - os: 'windows-latest'
          - os: 'macos-latest'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Qt
        uses: jurplel/install-qt-action@d325aaf2a8baeeda41ad0b5d39f84a6af9bcf005

      - name: Create build directory
        run: mkdir build

      - name: Generate build files
        run: qt-cmake -G Ninja -S . -B build

      - name: Build with Ninja
        run: cd build && ninja
